language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "cecbazinga"
    token: "3a652adc6c42958cc6a7d600e769ab152b33ae08"



install: mvn clean install -q -DskipTests=true

script:  mvn clean verify sonar:sonar -Dsonar.projectKey=CecBazinga_bookkeeper
